language: php
php:
- 5.6
sudo: false
script: make
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AmQkynOlZZFVLC4KmB1kBQl5nvLRalnZpTR44vxSbGhdKix/vI85pJe4P9iuLcH339FWJ7z7rDnhF9hPh8OaZOOaCbEzKOaqQiOYvavppFyVD7fb3L9eyCrbFzXQQ+LzWf0Q5i8OSiGklVbYOBtvjzsiKNiRXqFJwAxyo2MtIX2o1QVx2gho3Xrwab7gc+28jtJqfRh3mwFIpa4MsKkOYGBq0Tsn91Xpy06iVFEy+7SZYsZgq0PlCujBo+gJ4YwhSl1ojJjae0KOd4pqurLTul4B/SxAtsJW5Jt1KLJ8ClFpXUR+tAbRaVr1Svv0VIzHhJ8x5ddd2IAARbV+UYF2K54ElplhGDCUeYbBTsMTL9gdUsWUdFAWRD00+muRrAZgMWi0WM2Bzw+D1rRL2xvgm76CeKmgLYIGMksHMF/jUJvSYzzzykwqAmiQORwC+huZqDo60Aun2oBCpdqpsnRYyoHz+Fzcxpai6dQOJQnnX+14H4f2+5rxICmOgiaLkUuyrNxeFv56f7DQd0hFQegTCPu2hypBnMCxqcQ2JS6Co7jKHeXTmMigH5nus3jyXSIW7rf66tnwxBNiZtq+xOipUw1Y+2yGvk5jqxzGOmDCmMZh+rIywj9gjM9ifTxQdRKDs1JN4plifG3aH/QAJQpVeTqZsBVjM/9xxXhIGosz1gc=
  file: composer/composer.phar
  on:
    repo: yuloh/composer-termux
    tags: true
